### PR TITLE
Add jar to flink

### PR DESCRIPTION
**Pull request by MarieSaphira**
Automatically uploads the `jar-with-dependencies` taken from [here](http://archiva.clmsuk.com:8090/repository/internal/typhon/ac.york.typhon.analytics/0.0.1-SNAPSHOT/) to the flink container

### CODE REVIEW

**Comment by DavyLandman** [comment]
Hi @MarieSaphira, @patrickneubauer and @zolotas4  it looks like you are building an on the fly container with a jar downloaded at a certain time. Which means that it's a bit unclear which version you are getting, and after version bumping your release, old docker configs are broken and won't follow along.

I would prefer if the analytics team would make a docker container for their jar, like all the other components in the polystore.

The easiest path is using jib, it integrates into maven, and both the qlserver and the polystore api already use it. If you want help setting it up, let me know.

**Comment by DavyLandman** [comment]
(if I should move this discussion to a different issue or slack, please let me know)

**Comment by patrickneubauer** [comment]
Hi @DavyLandman @zolotas4 @MarieSaphira  
I added the jib plugin to the [analytics pom.xml](https://github.com/typhon-project/analytics/blob/ea7e8e2459354df984beec2fb7176f75af45b57b/ac.york.typhon.analytics/pom.xml#L207-L228) (this is in a feature branch) and found it to successfully deploy to a [Docker Hub repository](https://hub.docker.com/repository/docker/patrickneubauer/analytics). Could this help?

**Comment by DavyLandman** [comment]
great!

**Comment by MarieSaphira** [comment]
@patrickneubauer could you publish the Docker Hub repository? It's not accessible without logging in

**Comment by MarieSaphira** [comment]
@patrickneubauer  so how does the jobmanager get to know about the analytics image?

**Pull request merged**
